### ISSUE TITLE
not authorized on admin to execute command

### ISSUE THREAD

**Issue by agit05** [madhuneal/uptime#1]
Hello,
I have the following error when connecting to the MongoDB:

loading plugin ./plugins/console on app
loading plugin ./plugins/patternMatcher on app
loading plugin ./plugins/httpOptions on app
   info  - socket.io started
loading plugin ./plugins/patternMatcher on monitor
loading plugin ./plugins/httpOptions on monitor
Monitor origin started
Express server listening on host localhost, port 8082 in development mode
Mongoose: pings.ensureIndex({ timestamp: -1 }) { safe: undefined, background: true }
Mongoose: checkevents.ensureIndex({ timestamp: -1, check: 1 }) { safe: undefined, background: true }
Mongoose: checkhourlystats.ensureIndex({ timestamp: -1, check: 1 }) { safe: undefined, background: true, unique: true }
Mongoose: checkdailystats.ensureIndex({ timestamp: -1, check: 1 }) { safe: undefined, background: true, unique: true }
Mongoose: checkmonthlystats.ensureIndex({ timestamp: -1, check: 1 }) { safe: undefined, background: true, unique: true }
Mongoose: checkyearlystats.ensureIndex({ timestamp: -1, check: 1 }) { safe: undefined, background: true, unique: true }
Mongoose: taghourlystats.ensureIndex({ timestamp: -1, name: 1 }) { safe: undefined, background: true, unique: true }
Mongoose: tagdailystats.ensureIndex({ timestamp: -1, name: 1 }) { safe: undefined, background: true, unique: true }
Mongoose: tagmonthlystats.ensureIndex({ timestamp: -1, name: 1 }) { safe: undefined, background: true, unique: true }
Mongoose: tagyearlystats.ensureIndex({ timestamp: -1, name: 1 }) { safe: undefined, background: true, unique: true }
Mongoose: tags.ensureIndex({ name: 1 }) { safe: undefined, background: true, unique: true }
Mongoose: checks.find({ '$where': 'function () {\n if (this.isPaused) return false;\n if (!this.firstTested) return true;\n var delay = (this.lastTested.getTime() - this.firstTested.getTime()) % this.interval;\n return (Date.now() - this.lastTested.getTime() + delay) >= (this.interval || 60000);\n}' }) { fields: { qos: 0 }, safe: undefined }
{ [MongoError: not authorized on admin to execute command { serverStatus: 1 }]
  name: 'MongoError',
  ok: 0,
  errmsg: 'not authorized on admin to execute command { serverStatus: 1 }',
  code: 13 }

I wonder why does the app need to connect to the admin database and which should be the proper rights that the user should have it assigned on db ?

Thank you.
Constantin

**Comment by agit05** [comment]
Sorry, i found the issue.
You need to provide the monitoring user clusterAdmin role in MongoDB.

**Comment by lianyi** [comment]
I got the same issue...Could you help to elaborate a bit on how you solve the problem? I tried to add the _clusterAdmin_ Role but still having the same issue. 

``` javascript
      {
          [MongoError: not authorized on admin to execute command {
              serverStatus: 1
          }]
          name: 'MongoError',
          ok: 0,
          errmsg: 'not authorized on admin to execute command { serverStatus: 1 }',
          code: 13
      }
```
